class Config():
    TITLE = "Voxy's Word Counter"
    APP = "light"
    COLOR = "green"
    DESCRIPTION = "Please insert your words here"
    FONT = "Verdana"
    WRAP = "word"
    LABEL = "number of characters"
    INDEX = "end"
    BUTTON = "COUNT"
    DIMENSIONS = "375x400"
    WARNING = "Try again!"
    WARNING_TITLE = "WARNING"
    WARNING_BODY = "Some text input is required. Please try again!"
